INSERT INTO public.competitors (first_name, last_name, category)
VALUES ('Julio', 'Abraham', 'inter_m'),
  ('Caesar III', 'Altarejos', 'inter_m'),
  ('Harlan Red', 'Arias', 'inter_m'),
  ('Lytton', 'Artiaga', 'inter_m'),
  ('Jaime', 'Asturias', 'inter_m'),
  ('Forrest Kyle', 'Buscato', 'inter_m'),
  ('Boyet', 'Caballero', 'inter_m'),
  ('Jannuel Lauro', 'Dizon', 'inter_m'),
  ('Serge', 'Esguerra', 'inter_m'),
  ('Martin', 'Geron', 'inter_m'),
  ('Lorenzo', 'Guidote', 'inter_m'),
  ('Francisco Gerardo IV', 'Joaquin', 'inter_m'),
  ('John', 'Kikuchi', 'inter_m'),
  ('Ivan', 'Lagos', 'inter_m'),
  ('Justin', 'Lukban', 'inter_m'),
  ('Jose Luis', 'Mascardo', 'inter_m'),
  ('Isaac Emmanuel', 'Medina', 'inter_m'),
  ('Kyle', 'Ordoña', 'inter_m'),
  ('Brad Vincent', 'Palarca', 'inter_m'),
  ('John Ralph', 'Pancho', 'inter_m'),
  ('Keith', 'Plastina', 'inter_m'),
  ('Stephen', 'Quinia', 'inter_m'),
  ('Juan Gabriel', 'Samonte', 'inter_m'),
  ('Josef', 'Tolentino', 'inter_m'),
  ('Abigail Christiane', 'Arungayan', 'inter_w'),
  ('Angelica', 'Camacho', 'inter_w'),
  ('Michelle', 'Cruz', 'inter_w'),
  ('Alexene', 'Cruz-Herrera', 'inter_w'),
  ('Clana', 'Fontaine', 'inter_w'),
  ('Soleil', 'Ignacio', 'inter_w'),
  ('Anne Judiel', 'Pagkalinawan', 'inter_w'),
  ('Alessandra Jelena', 'Qui', 'inter_w'),
  ('Juan Miguel', 'Azupardo', 'open_m'),
  ('Ronald', 'Banlaoi', 'open_m'),
  ('Joseph Czar', 'Corpus', 'open_m'),
  ('Adrian Ponchai', 'Deetaisong', 'open_m'),
  ('Gerwin', 'Dimapilis', 'open_m'),
  ('Jonathan', 'Feleo', 'open_m'),
  ('John Rafael', 'Garrido', 'open_m'),
  ('Vicente', 'Gengos', 'open_m'),
  ('Mio', 'Gomez', 'open_m'),
  ('Jethro', 'Hallazgo', 'open_m'),
  ('Jhon Jhon Washington', 'Jusay', 'open_m'),
  ('Paulo Nicole', 'Laxina', 'open_m'),
  ('Zoren', 'Legaspi', 'open_m'),
  ('Eugenio', 'Lopez', 'open_m'),
  ('Joseph Merlou', 'Magpantay', 'open_m'),
  ('Iman Lorenzo', 'Mora', 'open_m'),
  ('Kranz', 'Moreno', 'open_m'),
  ('Andrei', 'Perjis', 'open_m'),
  ('Mich Danielle', 'Pinili', 'open_m'),
  ('Andrew Carl', 'Robles', 'open_m'),
  ('Emmanuelle', 'Salga', 'open_m'),
  ('James Oliver', 'Sia', 'open_m'),
  ('Jan Joseph', 'Suson', 'open_m'),
  ('Paul Eli', 'Suson', 'open_m'),
  ('Niño', 'Tabanao', 'open_m'),
  ('Matthew Benjamin', 'Tabios', 'open_m'),
  ('Edric', 'Uy', 'open_m'),
  ('John', 'Veloria', 'open_m'),
  ('Katrina', 'Abenojar', 'open_w'),
  ('Ananda', 'Abiad', 'open_w'),
  ('Sarah Angelica', 'Aquino', 'open_w'),
  ('Antonina Isabel', 'Arungayan', 'open_w'),
  ('Arriane Trixia', 'Bartolome', 'open_w'),
  ('Mei', 'Benedicto', 'open_w'),
  ('Jemima', 'Cabanlong', 'open_w'),
  ('Praj', 'dela Cruz', 'open_w'),
  ('Glory Ann Carmel', 'Dizon', 'open_w'),
  ('Megan', 'Francisco', 'open_w'),
  ('Maria Angela', 'Lapid', 'open_w'),
  ('Andrelin', 'Mora', 'open_w'),
  ('Liana Nicole', 'Mora', 'open_w'),
  ('Saihlene', 'Morata', 'open_w'),
  ('Jamie', 'Ng', 'open_w'),
  ('Kathrine Junalyn', 'Reyes', 'open_w'),
  ('Rochelle', 'Suarez', 'open_w'),
  ('Mhick', 'Tejares', 'open_w')