INSERT INTO public.qualis_problems (id,created_at,wall,description,points,color) VALUES
   (uuid_generate_v4(),NOW(),'Wall 1','0 pie',100,'red'),
   (uuid_generate_v4(),NOW(),'Wall 2','0 pie',100,'green'),
   (uuid_generate_v4(),NOW(),'Wall 3','0 pie',100,'blue'),
   (uuid_generate_v4(),NOW(),'Wall 4','0 pie',100,'yellow'),
   (uuid_generate_v4(),NOW(),'Wall 1','1 pie',200,'red'),
   (uuid_generate_v4(),NOW(),'Wall 2','1 pie',200,'green'),
   (uuid_generate_v4(),NOW(),'Wall 3','1 pie',200,'blue'),
   (uuid_generate_v4(),NOW(),'Wall 4','1 pie',200,'yellow'),
   (uuid_generate_v4(),NOW(),'Wall 1','2 pie',300,'red'),
   (uuid_generate_v4(),NOW(),'Wall 2','2 pie',300,'green'),
   (uuid_generate_v4(),NOW(),'Wall 3','2 pie',300,'blue'),
   (uuid_generate_v4(),NOW(),'Wall 4','2 pie',300,'yellow'),
   (uuid_generate_v4(),NOW(),'Wall 1','3 pie',400,'red'),
   (uuid_generate_v4(),NOW(),'Wall 2','3 pie',400,'green'),
   (uuid_generate_v4(),NOW(),'Wall 3','3 pie',400,'blue'),
   (uuid_generate_v4(),NOW(),'Wall 4','3 pie',400,'yellow'),
   (uuid_generate_v4(),NOW(),'Wall 1','4 pie',500,'red'),
   (uuid_generate_v4(),NOW(),'Wall 2','4 pie',500,'green'),
   (uuid_generate_v4(),NOW(),'Wall 3','4 pie',500,'blue'),
   (uuid_generate_v4(),NOW(),'Wall 4','4 pie',500,'yellow'),
   (uuid_generate_v4(),NOW(),'Wall 1','5 pie',600,'red'),
   (uuid_generate_v4(),NOW(),'Wall 2','5 pie',600,'green'),
   (uuid_generate_v4(),NOW(),'Wall 3','5 pie',600,'blue'),
   (uuid_generate_v4(),NOW(),'Wall 4','5 pie',600,'yellow'),
   (uuid_generate_v4(),NOW(),'Wall 1','6 pie',700,'red'),
   (uuid_generate_v4(),NOW(),'Wall 2','6 pie',700,'green'),
   (uuid_generate_v4(),NOW(),'Wall 3','6 pie',700,'blue'),
   (uuid_generate_v4(),NOW(),'Wall 4','6 pie',700,'yellow');

INSERT INTO public.teams (id,created_at,"name") VALUES
   (uuid_generate_v4(),NOW(),'Attack Team A'),
   (uuid_generate_v4(),NOW(),'Banda Bato?'),
   (uuid_generate_v4(),NOW(),'Charles Angels'),
   (uuid_generate_v4(),NOW(),'Dinner is Served'),
   (uuid_generate_v4(),NOW(),'Flying Ipis'),
   (uuid_generate_v4(),NOW(),'KrisTEAM'),
   (uuid_generate_v4(),NOW(),'Mara Wannabes'),
   (uuid_generate_v4(),NOW(),'Ninjas'),
   (uuid_generate_v4(),NOW(),'Parokya ni Dani'),
   (uuid_generate_v4(),NOW(),'Team Monke'),
   (uuid_generate_v4(),NOW(),'Team Llamatoe'),
   (uuid_generate_v4(),NOW(),'Tits and Tats');
   (uuid_generate_v4(),NOW(),'Weak is the New Strong'),
   (uuid_generate_v4(),NOW(),'1 Adult per 2 Children'),
   (uuid_generate_v4(),NOW(),'🐨'),