# fly.toml app configuration file generated for tallytop-sync on 2023-07-27T23:27:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tallytop-sync"
primary_region = "sin"

[http_service]
  internal_port = 1234
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source="tallytop_data"
  destination="/data"
