-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE public.competitors FROM anon;
REVOKE ALL ON TABLE public.competitors FROM authenticated;
REVOKE ALL ON TABLE public.competitors FROM postgres;
REVOKE ALL ON TABLE public.competitors FROM service_role;
REVOKE ALL ON TABLE public.competitors FROM supabase_admin;
GRANT ALL ON TABLE public.competitors TO supabase_admin;

GRANT ALL ON TABLE public.competitors TO authenticated;

GRANT ALL ON TABLE public.competitors TO anon;

GRANT ALL ON TABLE public.competitors TO postgres;

GRANT ALL ON TABLE public.competitors TO service_role;

REVOKE ALL ON TABLE public.divisions FROM anon;
REVOKE ALL ON TABLE public.divisions FROM authenticated;
REVOKE ALL ON TABLE public.divisions FROM service_role;
REVOKE ALL ON TABLE public.divisions FROM supabase_admin;
GRANT ALL ON TABLE public.divisions TO anon;

GRANT ALL ON TABLE public.divisions TO supabase_admin;

GRANT ALL ON TABLE public.divisions TO authenticated;

GRANT ALL ON TABLE public.divisions TO service_role;

REVOKE ALL ON TABLE public.rounds FROM anon;
REVOKE ALL ON TABLE public.rounds FROM authenticated;
REVOKE ALL ON TABLE public.rounds FROM service_role;
REVOKE ALL ON TABLE public.rounds FROM supabase_admin;
GRANT ALL ON TABLE public.rounds TO anon;

GRANT ALL ON TABLE public.rounds TO supabase_admin;

GRANT ALL ON TABLE public.rounds TO authenticated;

GRANT ALL ON TABLE public.rounds TO service_role;

REVOKE ALL ON TABLE public.attempts FROM anon;
REVOKE ALL ON TABLE public.attempts FROM authenticated;
REVOKE ALL ON TABLE public.attempts FROM postgres;
REVOKE ALL ON TABLE public.attempts FROM service_role;
REVOKE ALL ON TABLE public.attempts FROM supabase_admin;
GRANT ALL ON TABLE public.attempts TO anon;

GRANT ALL ON TABLE public.attempts TO postgres;

GRANT ALL ON TABLE public.attempts TO supabase_admin;

GRANT ALL ON TABLE public.attempts TO authenticated;

GRANT ALL ON TABLE public.attempts TO service_role;

ALTER TABLE IF EXISTS public.attempts
    ADD COLUMN count bigint;

REVOKE ALL ON TABLE public.advancements FROM anon;
REVOKE ALL ON TABLE public.advancements FROM authenticated;
REVOKE ALL ON TABLE public.advancements FROM postgres;
REVOKE ALL ON TABLE public.advancements FROM service_role;
REVOKE ALL ON TABLE public.advancements FROM supabase_admin;
GRANT ALL ON TABLE public.advancements TO anon;

GRANT ALL ON TABLE public.advancements TO postgres;

GRANT ALL ON TABLE public.advancements TO supabase_admin;

GRANT ALL ON TABLE public.advancements TO authenticated;

GRANT ALL ON TABLE public.advancements TO service_role;

REVOKE ALL ON TABLE public.climbs FROM anon;
REVOKE ALL ON TABLE public.climbs FROM authenticated;
REVOKE ALL ON TABLE public.climbs FROM service_role;
REVOKE ALL ON TABLE public.climbs FROM supabase_admin;
GRANT ALL ON TABLE public.climbs TO anon;

GRANT ALL ON TABLE public.climbs TO supabase_admin;

GRANT ALL ON TABLE public.climbs TO authenticated;

GRANT ALL ON TABLE public.climbs TO service_role;

REVOKE ALL ON TABLE public.comps FROM anon;
REVOKE ALL ON TABLE public.comps FROM authenticated;
REVOKE ALL ON TABLE public.comps FROM service_role;
REVOKE ALL ON TABLE public.comps FROM supabase_admin;
GRANT ALL ON TABLE public.comps TO anon;

GRANT ALL ON TABLE public.comps TO supabase_admin;

GRANT ALL ON TABLE public.comps TO authenticated;

GRANT ALL ON TABLE public.comps TO service_role;
