-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE qdb_2022.divisions FROM anon;
REVOKE ALL ON TABLE qdb_2022.divisions FROM authenticated;
REVOKE ALL ON TABLE qdb_2022.divisions FROM postgres;
REVOKE ALL ON TABLE qdb_2022.divisions FROM service_role;
REVOKE ALL ON TABLE qdb_2022.divisions FROM supabase_admin;
GRANT ALL ON TABLE qdb_2022.divisions TO anon;

GRANT ALL ON TABLE qdb_2022.divisions TO postgres;

GRANT ALL ON TABLE qdb_2022.divisions TO supabase_admin;

GRANT ALL ON TABLE qdb_2022.divisions TO authenticated;

GRANT ALL ON TABLE qdb_2022.divisions TO service_role;

ALTER TABLE IF EXISTS qdb_2022.attempts DROP COLUMN IF EXISTS id;

ALTER TABLE IF EXISTS qdb_2022.attempts
    RENAME id TO created_at;

ALTER TABLE qdb_2022.attempts
    ALTER COLUMN created_at TYPE timestamp with time zone ;
ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN created_at SET DEFAULT now();

ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE IF EXISTS qdb_2022.attempts
    RENAME id TO competitor_id;

ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN competitor_id DROP DEFAULT;

ALTER TABLE IF EXISTS qdb_2022.attempts
    RENAME id TO climb_id;

ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN climb_id DROP DEFAULT;

ALTER TABLE IF EXISTS qdb_2022.attempts
    RENAME id TO is_zone;

ALTER TABLE qdb_2022.attempts
    ALTER COLUMN is_zone TYPE boolean;
ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN is_zone DROP DEFAULT;

ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN is_zone DROP NOT NULL;

ALTER TABLE IF EXISTS qdb_2022.attempts
    RENAME id TO is_top;

ALTER TABLE qdb_2022.attempts
    ALTER COLUMN is_top TYPE boolean;
ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN is_top DROP DEFAULT;

ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN is_top DROP NOT NULL;

ALTER TABLE IF EXISTS qdb_2022.attempts
    RENAME id TO hold;

ALTER TABLE qdb_2022.attempts
    ALTER COLUMN hold TYPE numeric;
ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN hold DROP DEFAULT;

ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN hold DROP NOT NULL;

ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN hold SET STORAGE MAIN;

ALTER TABLE IF EXISTS qdb_2022.attempts
    RENAME id TO is_plus;

ALTER TABLE qdb_2022.attempts
    ALTER COLUMN is_plus TYPE boolean;
ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN is_plus DROP DEFAULT;

ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN is_plus DROP NOT NULL;

ALTER TABLE IF EXISTS qdb_2022.attempts
    RENAME id TO count;

ALTER TABLE qdb_2022.attempts
    ALTER COLUMN count TYPE bigint;
ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN count DROP DEFAULT;

ALTER TABLE IF EXISTS qdb_2022.attempts
    ALTER COLUMN count DROP NOT NULL;
ALTER TABLE IF EXISTS qdb_2022.attempts
    ADD CONSTRAINT attempts_pkey PRIMARY KEY (competitor_id, climb_id);

REVOKE ALL ON TABLE qdb_2022.rounds FROM anon;
REVOKE ALL ON TABLE qdb_2022.rounds FROM authenticated;
REVOKE ALL ON TABLE qdb_2022.rounds FROM postgres;
REVOKE ALL ON TABLE qdb_2022.rounds FROM service_role;
REVOKE ALL ON TABLE qdb_2022.rounds FROM supabase_admin;
GRANT ALL ON TABLE qdb_2022.rounds TO anon;

GRANT ALL ON TABLE qdb_2022.rounds TO postgres;

GRANT ALL ON TABLE qdb_2022.rounds TO supabase_admin;

GRANT ALL ON TABLE qdb_2022.rounds TO authenticated;

GRANT ALL ON TABLE qdb_2022.rounds TO service_role;

REVOKE ALL ON TABLE qdb_2022.climbs FROM anon;
REVOKE ALL ON TABLE qdb_2022.climbs FROM authenticated;
REVOKE ALL ON TABLE qdb_2022.climbs FROM postgres;
REVOKE ALL ON TABLE qdb_2022.climbs FROM service_role;
REVOKE ALL ON TABLE qdb_2022.climbs FROM supabase_admin;
GRANT ALL ON TABLE qdb_2022.climbs TO anon;

GRANT ALL ON TABLE qdb_2022.climbs TO postgres;

GRANT ALL ON TABLE qdb_2022.climbs TO supabase_admin;

GRANT ALL ON TABLE qdb_2022.climbs TO authenticated;

GRANT ALL ON TABLE qdb_2022.climbs TO service_role;

REVOKE ALL ON TABLE qdb_2022.comps FROM anon;
REVOKE ALL ON TABLE qdb_2022.comps FROM authenticated;
REVOKE ALL ON TABLE qdb_2022.comps FROM postgres;
REVOKE ALL ON TABLE qdb_2022.comps FROM service_role;
REVOKE ALL ON TABLE qdb_2022.comps FROM supabase_admin;
GRANT ALL ON TABLE qdb_2022.comps TO anon;

GRANT ALL ON TABLE qdb_2022.comps TO postgres;

GRANT ALL ON TABLE qdb_2022.comps TO supabase_admin;

GRANT ALL ON TABLE qdb_2022.comps TO authenticated;

GRANT ALL ON TABLE qdb_2022.comps TO service_role;
