-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE public.divisions FROM anon;
REVOKE ALL ON TABLE public.divisions FROM authenticated;
REVOKE ALL ON TABLE public.divisions FROM postgres;
REVOKE ALL ON TABLE public.divisions FROM service_role;
REVOKE ALL ON TABLE public.divisions FROM supabase_admin;
GRANT ALL ON TABLE public.divisions TO anon;

GRANT ALL ON TABLE public.divisions TO postgres;

GRANT ALL ON TABLE public.divisions TO supabase_admin;

GRANT ALL ON TABLE public.divisions TO authenticated;

GRANT ALL ON TABLE public.divisions TO service_role;

ALTER TABLE IF EXISTS public.attempts DROP COLUMN IF EXISTS id;

ALTER TABLE IF EXISTS public.attempts
    RENAME id TO created_at;

ALTER TABLE public.attempts
    ALTER COLUMN created_at TYPE timestamp with time zone ;
ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN created_at SET DEFAULT now();

ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE IF EXISTS public.attempts
    RENAME id TO competitor_id;

ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN competitor_id DROP DEFAULT;

ALTER TABLE IF EXISTS public.attempts
    RENAME id TO climb_id;

ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN climb_id DROP DEFAULT;

ALTER TABLE IF EXISTS public.attempts
    RENAME id TO is_zone;

ALTER TABLE public.attempts
    ALTER COLUMN is_zone TYPE boolean;
ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN is_zone DROP DEFAULT;

ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN is_zone DROP NOT NULL;

ALTER TABLE IF EXISTS public.attempts
    RENAME id TO is_top;

ALTER TABLE public.attempts
    ALTER COLUMN is_top TYPE boolean;
ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN is_top DROP DEFAULT;

ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN is_top DROP NOT NULL;

ALTER TABLE IF EXISTS public.attempts
    RENAME id TO hold;

ALTER TABLE public.attempts
    ALTER COLUMN hold TYPE numeric;
ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN hold DROP DEFAULT;

ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN hold DROP NOT NULL;

ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN hold SET STORAGE MAIN;

ALTER TABLE IF EXISTS public.attempts
    RENAME id TO is_plus;

ALTER TABLE public.attempts
    ALTER COLUMN is_plus TYPE boolean;
ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN is_plus DROP DEFAULT;

ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN is_plus DROP NOT NULL;

ALTER TABLE IF EXISTS public.attempts
    RENAME id TO count;

ALTER TABLE public.attempts
    ALTER COLUMN count TYPE bigint;
ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN count DROP DEFAULT;

ALTER TABLE IF EXISTS public.attempts
    ALTER COLUMN count DROP NOT NULL;
ALTER TABLE IF EXISTS public.attempts
    ADD CONSTRAINT attempts_pkey PRIMARY KEY (competitor_id, climb_id);

REVOKE ALL ON TABLE public.rounds FROM anon;
REVOKE ALL ON TABLE public.rounds FROM authenticated;
REVOKE ALL ON TABLE public.rounds FROM postgres;
REVOKE ALL ON TABLE public.rounds FROM service_role;
REVOKE ALL ON TABLE public.rounds FROM supabase_admin;
GRANT ALL ON TABLE public.rounds TO anon;

GRANT ALL ON TABLE public.rounds TO postgres;

GRANT ALL ON TABLE public.rounds TO supabase_admin;

GRANT ALL ON TABLE public.rounds TO authenticated;

GRANT ALL ON TABLE public.rounds TO service_role;

REVOKE ALL ON TABLE public.climbs FROM anon;
REVOKE ALL ON TABLE public.climbs FROM authenticated;
REVOKE ALL ON TABLE public.climbs FROM postgres;
REVOKE ALL ON TABLE public.climbs FROM service_role;
REVOKE ALL ON TABLE public.climbs FROM supabase_admin;
GRANT ALL ON TABLE public.climbs TO anon;

GRANT ALL ON TABLE public.climbs TO postgres;

GRANT ALL ON TABLE public.climbs TO supabase_admin;

GRANT ALL ON TABLE public.climbs TO authenticated;

GRANT ALL ON TABLE public.climbs TO service_role;

REVOKE ALL ON TABLE public.comps FROM anon;
REVOKE ALL ON TABLE public.comps FROM authenticated;
REVOKE ALL ON TABLE public.comps FROM postgres;
REVOKE ALL ON TABLE public.comps FROM service_role;
REVOKE ALL ON TABLE public.comps FROM supabase_admin;
GRANT ALL ON TABLE public.comps TO anon;

GRANT ALL ON TABLE public.comps TO postgres;

GRANT ALL ON TABLE public.comps TO supabase_admin;

GRANT ALL ON TABLE public.comps TO authenticated;

GRANT ALL ON TABLE public.comps TO service_role;
